name: ulenguage_app_n
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0         # <-- Versión compatible con flutter_localizations
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  image_picker: ^1.0.4
  provider: ^6.1.5+1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.0
  sign_in_with_apple: ^7.0.1
  connectivity_plus: ^7.0.0
  firebase_auth: ^6.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.6
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/apple_icon.png
    - assets/inka.png
    - assets/ocr_imaynallam.png
    - assets/ocr_salesmanager.jpeg
    - assets/Machu_Picchu.jpg
    - assets/centro_historico.jpg
    - assets/Ollantaytambo.jpg
    - assets/map_cusco.png

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFPRODISPLAYREGULAR.OTF